apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: app-ns
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: abhinav0101/flask-app
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: mysql-service.sql-ns.svc.cluster.local
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DB
          value: mydb
